import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

import { AZURE_ICON_COLLECTIONS, AZURE_TOPBAR_ICON_NAMES } from './lib/azureIcons'

const MDI_ICON_NAMES = [
  'mdi:alert-circle',
  'mdi:alert-circle-outline',
  'mdi:arrow-right-thin',
  'mdi:account-group',
  'mdi:application',
  'mdi:auto-fix',
  'mdi:badge-account',
  'mdi:bolt',
  'mdi:calendar-month-outline',
  'mdi:castle',
  'mdi:check',
  'mdi:checkbox-blank-circle-outline',
  'mdi:checkbox-marked-circle',
  'mdi:check-circle',
  'mdi:check-circle-outline',
  'mdi:chevron-down',
  'mdi:chevron-right',
  'mdi:clipboard-check-outline',
  'mdi:close-circle',
  'mdi:close-circle-outline',
  'mdi:connection',
  'mdi:content-save-alert',
  'mdi:content-save-check',
  'mdi:content-save-outline',
  'mdi:counter',
  'mdi:database',
  'mdi:dns',
  'mdi:draw',
  'mdi:ethernet',
  'mdi:file-multiple',
  'mdi:fit-to-page',
  'mdi:fit-to-page-outline',
  'mdi:flask-outline',
  'mdi:fullscreen',
  'mdi:folder-open-outline',
  'mdi:function',
  'mdi:grid',
  'mdi:harddisk',
  'mdi:help-circle',
  'mdi:image-off',
  'mdi:info-circle',
  'mdi:ip-network',
  'mdi:key',
  'mdi:kubernetes',
  'mdi:lan',
  'mdi:laptop',
  'mdi:lightning-bolt',
  'mdi:lock',
  'mdi:lock-open-variant',
  'mdi:magic-staff',
  'mdi:map-marker-path',
  'mdi:markdown-outline',
  'mdi:magnify-minus-outline',
  'mdi:magnify-plus-outline',
  'mdi:network',
  'mdi:paper-plane-outline',
  'mdi:party-popper',
  'mdi:play',
  'mdi:plus',
  'mdi:router-network',
  'mdi:routes',
  'mdi:scale-balance',
  'mdi:server',
  'mdi:server-network',
  'mdi:shield-check',
  'mdi:shield-lock',
  'mdi:shield-lock-outline',
  'mdi:sitemap-outline',
  'mdi:speedometer',
  'mdi:test-tube',
  'mdi:test-tube-empty',
  'mdi:timer-alert-outline',
  'mdi:transit-connection',
  'mdi:trash',
  'mdi:user',
  'mdi:user-plus',
  'mdi:vector-arrange-above',
  'mdi:vector-polygon',
  'mdi:vector-square',
  'mdi:vpn',
  'mdi:wall-fire',
  'mdi:web',
  'mdi:xml',
]

const currentDir = dirname(fileURLToPath(import.meta.url))

export default defineNuxtConfig({
  ssr: false,
  compatibilityDate: '2026-04-30',
  devtools: { enabled: false },
  components: {
    dirs: [
      { path: '~/components', pathPrefix: false },
    ],
  },
  modules: [
    '@nuxt/icon',
    '@primevue/nuxt-module',
    '@pinia/nuxt',
  ],
  icon: {
    provider: 'none',
    customCollections: AZURE_ICON_COLLECTIONS.map(collection => ({
      prefix: collection.prefix,
      dir: resolve(currentDir, collection.dir),
    })),
    clientBundle: {
      icons: [...AZURE_TOPBAR_ICON_NAMES, ...MDI_ICON_NAMES],
      includeCustomCollections: true,
    },
  },
  primevue: {
    importTheme: { as: 'PrimeVueTheme', from: '~/assets/primevue-theme.ts' },
    options: {
      ripple: true,
    },
    // Restrict auto-import to only the components actually used in this project.
    // The default (include: '*') registers all 100+ PrimeVue components as Vite
    // modules, each with an associated Style module — causing steady heap growth
    // in dev mode as the module graph accumulates across HMR cycles.
    components: {
      include: [
        'Accordion', 'AccordionContent', 'AccordionHeader', 'AccordionPanel',
        'Button',
        'Checkbox',
        'Dialog',
        'Divider',
        'InputNumber', 'InputText',
        'Message',
        'MeterGroup',
        'Password',
        'ProgressBar', 'ProgressSpinner',
        'Select', 'SelectButton',
        'Tabs', 'Tab', 'TabList', 'TabPanel', 'TabPanels',
        'Tag',
        'Textarea',
        'ToggleSwitch',
        'Tooltip',
      ],
    },
  },
  css: [
    'primeicons/primeicons.css',
    '@vue-flow/core/dist/style.css',
    '@vue-flow/controls/dist/style.css',
    '~/assets/css/main.css',
    '~/assets/css/diagram.css',
  ],
  runtimeConfig: {
    public: {
      awsRegion: process.env.NUXT_PUBLIC_AWS_REGION || 'us-east-1',
      cognitoUserPoolId: process.env.NUXT_PUBLIC_COGNITO_USER_POOL_ID || '',
      cognitoClientId: process.env.NUXT_PUBLIC_COGNITO_CLIENT_ID || '',
      cognitoIdentityPoolId: process.env.NUXT_PUBLIC_COGNITO_IDENTITY_POOL_ID || '',
      s3Bucket: process.env.NUXT_PUBLIC_S3_BUCKET || '',
      bedrockRegion: process.env.NUXT_PUBLIC_BEDROCK_REGION || 'us-east-1',
      mongodbEndpoint: process.env.NUXT_PUBLIC_MONGODB_ENDPOINT || '',
      mongodbDatabase: process.env.NUXT_PUBLIC_MONGODB_DATABASE || 'vnet-simulator',
      mongodbCollection: process.env.NUXT_PUBLIC_MONGODB_COLLECTION || 'user_settings',
    },
  },
  vite: {
    optimizeDeps: {
      include: ['dagre', '@vue-flow/core', '@vue-flow/background', '@vue-flow/controls', '@vue-flow/minimap'],
    },
    worker: {
      format: 'es',
    },
  },
  app: {
    head: {
      title: 'Azure Virtual Network Simulator',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'Interactive Azure Virtual Network topology designer and simulator' },
      ],
      link: [
        { rel: 'icon', type: 'image/svg+xml', href: '/virtual-networks.svg' },
      ],
    },
  },
})
